["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

[profile.ci.protostar.shared_command_configs]
no_color=true

["protostar.shared_command_configs"]
cairo_path = ["contracts", "lib/cairo_contracts/src"]

["protostar.test"]
target = ["contracts"]

["protostar.contracts"]
badge_registry = [ "./contracts/onlydust/deathnote/core/badge_registry/badge_registry.cairo" ]
badge = [ "./contracts/onlydust/deathnote/core/badge/badge.cairo" ]
github_contributions = [ "./contracts/onlydust/deathnote/core/contributions/github/github.cairo" ]
